[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
serde = "1.0.136"
tracing = { version = "0.1.32", features = ["log"] }
tracing-log = "0.1.2"
tracing-actix-web = "0.5.1"
tracing-subscriber = { version = "0.3.9", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3.2"
validator = { version = "0.15.0", features = ["derive"] }
uuid = { version = "0.8.2", features = ["v4"] } # sqlx-core requires 0.8.2
secrecy = { version = "0.8.0", features = ["serde"] }
sqlx = { version = "0.5.13", features = ["postgres", "uuid", "offline", "runtime-actix-rustls"] }
chrono = { version = "0.4.19", features = ["serde"] }
dotenv = "0.15.0"

[dev-dependencies]
once_cell = "1.10.0"
fake = "2.4.3"
